### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by LuxyNerd** [emiTu/Targeting-in-VR#1]
## **Study Design**
- Was ist der Grund der Studie
- Was was will man herausfinden
- Was ist die Methode
- Wie gut zielen die Leute?
- Wie lange brauchen die Leute?
- Wie genau sind sie das Ziel? ( hier die "Wackelstärke" messen )
- Einflussgrößen geben: Man hält den Controller mit ausgestrecktem Arm oder stützt man den   Ellenbogen ab?

- [ ] Consent Form
- [ ] Questionnaires

## **Prototyp**
Targeting (vive controller <- wie gut kann man damit "pointen")

###  Visualisierung (was sehe ich)
   - [ ] Condition 1: Fadenkreuz, mit dem man Korrigieren kann
   - [ ] Condition 2: Man sieht einen Laserstrahl
   - [ ] Condition 3: Man sieht einen Fadenkreuz und einen Laserstrahl
   - [ ] Condition 4: Man sieht nicht, wo man hintrifft  (evtl.)

###   Distanz zum Ziel
   - [ ] Sehr nah
   - [ ] Weiter weg
   - [ ] Sehr weit weg

## **Szenario**
- Wand, die unterschiedliche Distanzen einnehmen kann ( 5m - 10m - 15m)
- Die drei Visualisierungsmöglichkeiten einbauen (dafür sollen/sollten wir ein Paper bekommen)
- Messgrößen: Zeit, Genauigkeit und ??[Lücke]

## **Questionnaire**
- Wie gut hat es Dir gefallen?
- Welche Visualisierung bevorzugst Du?
- Wo glaubst Du, wo Du am Besten warst?

**Comment by LuxyNerd** [comment]
- DeadLine =Vor Weihnachten
- Nach Weihnachten = Durchführung der Studie
